# Generated by Django 2.0.6 on 2018-09-01 23:57

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('v1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='address',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='course',
            name='holes',
            field=models.ManyToManyField(to='v1.Hole'),
        ),
        migrations.AddField(
            model_name='course',
            name='name',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='game',
            name='course',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='v1.Course'),
        ),
        migrations.AddField(
            model_name='game',
            name='date',
            field=models.DateTimeField(default=datetime.date.today, verbose_name='date played'),
        ),
        migrations.AddField(
            model_name='game',
            name='players',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='game',
            name='scores',
            field=models.ManyToManyField(to='v1.Score'),
        ),
        migrations.AddField(
            model_name='hole',
            name='number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hole',
            name='par',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hole',
            name='yardage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='score',
            name='hole',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='v1.Hole'),
        ),
        migrations.AddField(
            model_name='score',
            name='player',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='score',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
