# Generated by Django 2.0.6 on 2018-09-02 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0003_auto_20180902_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='holes',
            field=models.ManyToManyField(blank=True, related_name='_course_holes_+', to='v1.Hole'),
        ),
        migrations.AlterField(
            model_name='hole',
            name='course',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='v1.Course'),
        ),
    ]
