# Generated by Django 2.0.6 on 2018-09-02 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0004_auto_20180902_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='length',
            field=models.IntegerField(default=9),
        ),
    ]
