# Generated by Django 2.0.6 on 2018-09-02 23:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0007_auto_20180902_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='date',
            field=models.DateTimeField(default=datetime.date(2018, 9, 2), verbose_name='date played'),
        ),
    ]
