# Generated by Django 2.0.6 on 2018-09-02 23:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0008_auto_20180902_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date played'),
        ),
    ]
